baseURL = "https://caiotedim.github.io/"
languageCode = "pt-br"
title = "Caio Tedim"
copyright = "© {year}"

themesDir = "./themes/"
publishDir = "./docs/"

theme = ["resume"]

PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[params]
address = "São Paulo, BR"
email = "caiotedim[@]gmail[.]com"
firstName = "Caio"
lastName = "Tedim"
dateFormat = "January 2, 2006"
profileImage = "./img/profile.jpg"
favicon = "./favicon.ico"
showCertificatons = false
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showQr = true
showSkills = true
showPageTitleInTOC = true

[[params.handles]]
link = "https://linkedin.com/in/caiotedim"
name = "LinkedIn"

[[params.handles]]
link = "https://twitter.com/caiotedim"
name = "Twitter"

[[params.handles]]
link = "https://github.com/caiotedim"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"

[module]
[module.hugoVersion]
min = "0.101.0"
