baseURL = "https://caiotedim.github.io/"
languageCode = "pt-br"
title = "Caio Tedim Francisco"
themesDir = "./themes/"
publishDir = "./docs/"

theme = ["soho"]

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[params]
author = "Caio Tedim Francisco"
description = ""
copyright = "Caio Tedim Francisco"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
customCss = ["css/blog.css"]
customJs = ["js/blog.js"]

email = "me@caiotedim.dev"
dateFormat = "January 2, 2006"
profilePicture = "./img/profile.jpg"

[[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://linkedin.com/in/caiotedim"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/caiotedim"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/caiotedim"

[menu]

  [[menu.main]]
  name = "Blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true # if false, you need to provide you own custom CSS
  style = "monokai"
  tabWidth = 4

[module]
[module.hugoVersion]
min = "0.101.0"
