baseURL = "https://caiotedim.dev:1313/"
languageCode = "pt-br"
title = "Caio Tedim"
copyright = "© {year}"

themesDir = "./themes/"

theme = ["resume"]

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[params]
dateFormat = "2 Jan 2006"
showPageTitleInTOC = true

linkedin = "https://linkedin.com/in/caiotedim"
twitter = "https://twitter.com/caiotedim"
github = "https://github.com/caiotedim"

iconOrder = ["LinkedIn", "GitHub", "Twitter"]

[markup]
  [markup.highlight]
    codeFences = false

  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
